apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: remove-files
      image: alpine:3.14
      command: ["rm"]
      args: ["-rf", "/workspace/*"]
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-tests
spec:
  steps:
    - name: run-tests
      image: python:3.8
      script: |
        pip install nose
        pip install -r requirements.txt
        nosetests
