apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Cleaning up temporary files..."
        rm -rf /tmp/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task
spec:
  steps:
    - name: run-tests
      image: python:3.10
      script: |
        #!/bin/bash
        echo "Installing dependencies..."
        pip install nose
        echo "Running tests..."
        nosetests test.py
